### ISSUE TITLE
minor code issues

### ISSUE THREAD

**Issue by ThomasWaldmann** [Daeinar/norx-py#2]
aside from #1 (which is mostly cosmetic/formatting related), there are also some minor issues that rather relate to the code itself, like:

using old-style classes
remove unused imports

using assert (maybe, depending on whether you want it ALWAYS checked or not)
(non-usage) of exceptions, usage of inband signalling
other stuff pylint or other checker may find

do you want pull request for that?

**Comment by Daeinar** [comment]
Again, feel free to send a pull request. Please make sure that the [test vectors](https://github.com/Daeinar/norx-py/blob/master/main.py) still pass after you've applied your changes.

Thanks for your help!

**Comment by ThomasWaldmann** [comment]
see pull request #3.

**Comment by ThomasWaldmann** [comment]
Fixed first 2, see pull request #4.

About assert: If Python is started with the -O option, then assertions will be stripped out and not evaluated. Is this what you want? Or do you rather want the checks executed in every case and an exception thrown if they fail?

Also, it could throw an exception if signature check fails rather than return an empty string.

**Comment by ThomasWaldmann** [comment]
PR #4 was merged.
